import { availableColours } from "../../templates/utils/colours";

export const colours = availableColours;
export const sizes = ["xs", "sm", "md", "lg", "xl"] as const;
export const textSizes = [
    "xs",
    "sm",
    "md",
    "lg",
    "xl",
    "2xl",
    "3xl",
    "4xl",
    "5xl",
    "6xl",
    "7xl",
] as const;
export const variants = [
    "solid",
    "outline",
    "subtle",
    "ghost",
    "surface",
    "plain",
    "glass",
    "enclosed",
] as const;
export const buttonVariants = [
    "solid",
    "outline",
    "subtle",
    "ghost",
    "surface",
    "plain",
    "glass",
] as const;
export const checkboxVariants = ["outline", "subtle", "solid"] as const;
export const inputVariants = ["outline", "subtle", "flushed"] as const;
export const alertStatuses = [
    "info",
    "success",
    "warning",
    "error",
    "neutral",
] as const;
export const orientations = ["vertical", "horizontal"] as const;
export const placements = ["top", "bottom", "left", "right", "center"] as const;

export const commonArgTypes = {
    variant: {
        control: "select",
        options: variants,
        description: "The visual style of the component.",
        table: { defaultValue: { summary: "solid" } },
    },
    size: {
        control: "select",
        options: sizes,
        description: "The size of the component.",
        table: { defaultValue: { summary: "md" } },
    },
    colour: {
        control: "select",
        options: colours,
        description: "The colour theme of the component.",
        table: { defaultValue: { summary: "gray" } },
    },
    disabled: {
        control: "boolean",
        description: "Whether the component is disabled.",
        table: { defaultValue: { summary: "false" } },
    },
    invalid: {
        control: "boolean",
        description: "Whether the component is in an invalid state.",
        table: { defaultValue: { summary: "false" } },
    },
    children: {
        control: false,
        description: "The content to be rendered inside the component.",
        table: { type: { summary: "Snippet" } },
    },
    class: {
        control: "text",
        description: "Additional CSS classes to apply.",
    },
    icon: {
        control: "boolean",
        description: "The icon to display.",
    },
} as const;

// Re-export from hide-inherited-props
import { generateExcludePattern as genExcludePattern } from "./hide-inherited-props";
export { generateExcludePattern } from "./hide-inherited-props";

// Re-export all patterns from exclude-patterns
export {
    accordionRootPattern,
    accordionItemPattern,
    accordionItemTriggerPattern,
    accordionItemContentPattern,
    alertPattern,
    buttonPattern,
    checkboxPattern,
    checkboxGroupPattern,
    dialogRootPattern,
    drawerRootPattern,
    iconPattern,
    inputPattern,
    inputGroupPattern,
    inputElementPattern,
    stackPattern,
    textPattern,
    tooltipPattern,
    fieldPattern,
    fieldLabelPattern,
    fieldHelperTextPattern,
    fieldErrorTextPattern,
    kbdPattern,
    codePattern,
    visuallyHiddenPattern,
    badgePattern,
    avatarPattern,
    avatarGroupPattern,
    groupPattern,
    dataListRootPattern,
    dataListItemPattern,
    dataListItemLabelPattern,
    dataListItemValuePattern,
    blockquotePattern,
    floatPattern,
    circlePattern,
    boxPattern,
    headingPattern,
    emPattern,
    markPattern,
    highlightPattern,
    toastPattern,
    actionBarPattern,
    actionBarSelectionTriggerPattern,
    actionBarSeparatorPattern,
    actionBarCloseButtonPattern,
    breadcrumbRootPattern,
    breadcrumbItemPattern,
    breadcrumbLinkPattern,
    breadcrumbCurrentLinkPattern,
    breadcrumbEllipsisPattern,
    menuPattern,
    menuItemPattern,
    cardRootPattern,
    cardHeaderPattern,
    cardBodyPattern,
    cardFooterPattern,
    cardTitlePattern,
    cardDescriptionPattern,
    formPattern,
    formFieldPattern,
    submitButtonPattern,
    displayIfPattern,
    checkboxCardRootPattern,
    checkboxCardControlPattern,
    checkboxCardContentPattern,
    checkboxCardLabelPattern,
    checkboxCardDescriptionPattern,
    checkboxCardAddonPattern,
    checkboxCardIndicatorPattern,
    comboboxPattern,
    comboboxRootPattern,
    comboboxControlPattern,
    comboboxInputPattern,
    comboboxContentPattern,
    comboboxItemPattern,
    comboboxItemTextPattern,
    comboboxItemIndicatorPattern,
    popoverRootPattern,
    popoverTriggerPattern,
    popoverContentPattern,
    popoverArrowPattern,
    popoverHeaderPattern,
    popoverBodyPattern,
    popoverFooterPattern,
    popoverTitlePattern,
    popoverDescriptionPattern,
    popoverCloseTriggerPattern,
    navbarRootPattern,
    navbarContentPattern,
    navbarBrandPattern,
    navbarItemGroupPattern,
    navbarItemPattern,
    navbarLinkPattern,
    sidebarRootPattern,
    sidebarHeaderPattern,
    sidebarBodyPattern,
    sidebarFooterPattern,
    sidebarGroupPattern,
    sidebarGroupHeaderPattern,
    sidebarGroupTitlePattern,
    sidebarGroupContentPattern,
    sidebarNavItemPattern,
    sidebarNavButtonPattern,
    sidebarItemPattern,
    sidebarLinkPattern,
    sidebarTogglePattern,
    appShellPattern,
    editablePattern,
    editableAreaPattern,
    editablePreviewPattern,
    editableInputPattern,
    editableTextareaPattern,
    editableControlPattern,
    editableLabelPattern,
    editableTriggerPattern,
    listRootPattern,
    listItemPattern,
    listIndicatorPattern,
    emptyStatePattern,
    fileUploadRootPattern,
    fileUploadTriggerPattern,
    fileUploadDropzonePattern,
    fileUploadListPattern,
    fileUploadLabelPattern,
    fileUploadInputPattern,
    fileUploadClearTriggerPattern,
    gridListRootPattern,
    gridListHeaderPattern,
    gridListItemPattern,
    gridListCellPattern,
    tagPattern,
} from "./exclude-patterns";



export const getControls = (allowedProps: string[]) => {
    return {
        exclude: genExcludePattern(allowedProps),
    };
};
